defaults:
  # Config
  - hydra: default 
  - extras: default
  - paths: default
  
  # Model
  - solver: default
  - writer: default
  - model: classifier
  - test: default

  #
  - _self_

project: test
name: vlformer-bs8x8-150ep
id: ${now:%Y-%m-%d_%H-%M-%S}
seed: 19052801

hydra:
  run:
    dir: outputs/${project}/${name}/${id}